name: x86_64-vdso

on:
  push:
    branches:
      - master2


jobs:

  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-x86_64-gcc-13
      gcc_prefix: x86_64-openadk-linux-uclibc-
      kernel_vers: 4.19.56
      kernel_dir: v4.x
      kernel_arch: x86_64
      config_file: config.x86_64_shared_vdso
      qemu_kernel: 
      qemu_cmd: 

  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    secrets: inherit
