name: mips64le-n32-4.19.56

on:
  push:
    branches:
      - disabled

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install dev packages
        run: |
          sudo apt-get update
          sudo apt-get install tar
      
      - name: Install Toolchain
        run: |
           wget "https://github.com/lordrasmus/toolchains/blob/main/toolchain_generic-mips64_uclibc-ng_mips64el_n32.tar.xz?raw=true" -O toolchain_generic-mips64_uclibc-ng_mips64el_n32.tar.xz
           tar -xaf toolchain_generic-mips64_uclibc-ng_mips64el_n32.tar.xz
           
      - name: add PATH
        run: echo "$(pwd)/toolchain_generic-mips64_uclibc-ng_mips64el_n32/usr/bin/" >> $GITHUB_PATH

      - name: Extract Kernel Headers
        run: wget "https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.19.56.tar.xz" -O linux-4.19.56.tar.xz && tar -xaf linux-4.19.56.tar.xz
        
      - name: Install Kernel Headers
        run: make -C linux-4.19.56/ INSTALL_HDR_PATH=$(pwd)/linux-headers/ headers_install ARCH=mips

      - name: Run shared
        run: cp .github/workflows/config.mips64le-n32 .config && CROSS_COMPILE=mips64el-openadk-linux-uclibcabin32- make

      
