name: nios2

on:
  push:
    branches:
      - master



jobs:

  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-nios2-gcc-13
      gcc_prefix: nios2-openadk-linux-uclibc-
      kernel_vers: 6.1.53
      kernel_dir: v6.x
      kernel_arch: nios2
      config_file: config.nios2
      qemu_kernel: 
      qemu_cmd: 

  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    
