name: x86_64

on:
  push:
    branches:
      - disabled

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install dev packages
        run: |
          sudo apt-get update
          sudo apt-get install gcc

      - name: Extract Kernel Headers
        run: wget "https://github.com/lordrasmus/toolchains/blob/main/linux-4.19.56.tar.xz?raw=true" -O linux-4.19.56.tar.xz && tar -xaf linux-4.19.56.tar.xz
      - name: Install Kernel Headers
        run: make -C linux-4.19.56/ INSTALL_HDR_PATH=$(pwd)/linux-headers/ headers_install ARCH=x86_64

      - name: Run shared
        run: cp .github/workflows/config.x86_64_shared .config && make

      - name: Run static
        run: cp .github/workflows/config.x86_64_static .config && make

      - name: Run shared vdso
        run: cp .github/workflows/config.x86_64_shared_vdso .config && make

      - name: Run shared vdso
        run: cp .github/workflows/config.x86_64_static_vdso .config && make
