name: powerpc

on:
  push:
    branches:
      - master

      

#config.powerpc-vdso
#config.powerpc-no-vdso

jobs:

  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-ppc-gcc-12_soft
      gcc_prefix: ppc-openadk-linux-uclibc-
      kernel_vers: 4.19.56
      kernel_dir: v4.x
      kernel_arch: powerpc
      config_file: config.powerpc
      qemu_kernel: 
      qemu_cmd: 

  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    
