name: sparc-v8-lt-gcc-10-kernel-4.19.56-shared-elf

on:
  workflow_dispatch:
  repository_dispatch:
    types: [test-update]
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

      
jobs:

  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-sparc_v8-gcc-10
      gcc_prefix: sparc-openadk-linux-uclibc-
      kernel_vers: 4.19.56
      kernel_dir: v4.x
      kernel_arch: sparc
      config_file: config.sparc_linuxthreads
      qemu_kernel: kernel-sparc-smp.img
      qemu_cmd: qemu-system-sparc -monitor none -parallel none -net none -M SS-20 -smp 4 -m 256 -kernel kernel.img  -initrd rootfs.img.xz -nographic

  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    secrets: inherit
    
    
  call_qemu:
    needs: call_images
    uses: ./.github/workflows/z_qemu_test_run.yml
    secrets: inherit

  call_badge_failed:
    if: failure()
    needs: [call_build, call_images]
    uses: ./.github/workflows/z_badge_failed_workflow.yml
    with:
      build_result: ${{ needs.call_build.result }}
      images_result: ${{ needs.call_images.result }}
    secrets: inherit
