name: mips64-n32-6.1.60

on:
  push:
    branches:
      - master



jobs:

  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-mips64_mips64-gcc-13_n32
      gcc_prefix: mips64-openadk-linux-uclibcabin32-
      kernel_vers: 6.1.60
      kernel_dir: v6.x
      kernel_arch: mips
      config_file: config.mips64-n32
      qemu_kernel: 
      qemu_cmd: 

  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    secrets: inherit
    
