name: bfin

on:
  push:
    branches:
      - master2


      
jobs:
      
  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-bfin_bf512-gcc-13_flat_nommu
      gcc_prefix: bfin-openadk-uclinux-uclibc-
      kernel_vers: 4.9.156
      kernel_dir: v4.x
      kernel_arch: blackfin
      config_file: config.bfin2
      qemu_kernel: 
      qemu_cmd: 


  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    secrets: inherit
    
