name: x86

on:
  push:
    branches:
      - master


#      - name: Run static
#        run: cp .github/workflows/config.x86_64_static .config && make

#      - name: Run shared vdso
#        run: cp .github/workflows/config.x86_64_static_vdso .config && make


jobs:

  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-i686-gcc-13
      gcc_prefix: i686-openadk-linux-uclibc-
      kernel_vers: 4.19.56
      kernel_dir: v4.x
      kernel_arch: x86
      config_file: config.x86
      qemu_kernel:  kernel-x86.img
      qemu_cmd:  qemu-system-i386 -m 1G -smp 4 -append "console=ttyS0" -nographic  -kernel kernel.img -initrd rootfs.img

  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    secrets: inherit


  call_qemu:
    permissions:
     checks: write
     pull-requests: write
     
    needs: call_images
    uses: ./.github/workflows/z_qemu_test_run.yml
    secrets: inherit
