name: riscv64-npt-gcc-10-kernel-4.19.56-static-elf

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master



jobs:

  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-riscv64-gcc-10.5.0_static
      gcc_prefix: riscv64-openadk-linux-uclibc-
      kernel_vers: 4.19.56
      kernel_dir: v4.x
      kernel_arch: riscv
      config_file: config.riscv64_static
      qemu_kernel: kernel-riscv64.img
      qemu_cmd: qemu-system-riscv64 -M virt -m 512 -nographic -append console=ttyS0  -kernel kernel.img -initrd rootfs.img.xz


  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    secrets: inherit


  call_qemu:    
    needs: call_images
    uses: ./.github/workflows/z_qemu_test_run.yml
    secrets: inherit
