name: c6x-le-no-gcc-7-kernel-4.9.156-static-nommu-flat

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

      
      
jobs:
      
  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-c6x-gcc-7_nommu
      gcc_prefix: tic6x-openadk-uclinux-
      kernel_vers: 4.9.156
      kernel_dir: v4.x
      kernel_arch: c6x
      config_file: config.c6x
      qemu_kernel: 
      qemu_cmd: 


#  call_images:
#    needs: call_build
#    uses: ./.github/workflows/z_images_workflow.yml
#    secrets: inherit
