name: cris-no-gcc-10-kernel-4.9.156-shared-elf

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
      
  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-cris_crisv10-gcc-10
      gcc_prefix: cris-openadk-linux-uclibc-
      kernel_vers: 4.9.156
      kernel_dir: v4.x
      kernel_arch: cris
      config_file: config.cris
      qemu_kernel: 
      qemu_cmd: 

  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    secrets: inherit
    
