name: sparc_linuxthreads-4.19.56

on:
  push:
    branches:
      - master

      
jobs:

  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-sparc_v8-gcc-10
      gcc_prefix: sparc-openadk-linux-uclibc-
      kernel_vers: 4.19.56
      kernel_dir: v4.x
      kernel_arch: sparc
      config_file: config.sparc_linuxthreads
      qemu_kernel: 
      qemu_cmd: 

  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    
