name: tile-4.14.311

on:
  push:
    branches:
      - master


jobs:

  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-tilegx-gcc-10
      gcc_prefix: tilegx-openadk-linux-uclibc-
      kernel_vers: 4.14.311
      kernel_dir: v4.x
      kernel_arch: tile
      config_file: config.tile
      qemu_kernel: 
      qemu_cmd: 

  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    secrets: inherit
