name: m68k

on:
  push:
    branches:
      - master

jobs:
      
  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-m68k_cf51-gcc-13
      gcc_prefix: m68k-openadk-uclinux-uclibc-
      kernel_vers: 5.4.259
      kernel_dir: v5.x
      kernel_arch: m68k
      config_file: config.m68k
      qemu_kernel: 
      qemu_cmd: 

#  call_images:
#    needs: call_build
#    uses: ./.github/workflows/z_images_workflow.yml
    
