name: xtensa-4.19.56

on:
  push:
    branches:
      - master


jobs:


  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-xtensa_dc232b-gcc-13.2.0
      gcc_prefix: xtensa-openadk-linux-uclibc-
      kernel_vers: 4.19.56
      kernel_dir: v4.x
      kernel_arch: xtensa
      config_file: config.xtensa_mmu
      qemu_kernel: kernel-xtensa.img
      qemu_cmd: qemu-system-xtensa -M lx200 -cpu dc233c -m 128M  -monitor null -nographic -kernel kernel.img
      #
      # mit -pflash soll man ein flash device im qemu erzeugen können, bis jetzt konnt ich das aber nicht zu laufen bringen
      # darum erstmal der cpio hack
      # qemu-system-xtensa -M lx200 -cpu dc233c -monitor null -nographic -kernel kernel.img  -pflash  rootfs.squash -m 128M
      #

  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    secrets: inherit


  call_qemu:
    needs: call_images
    uses: ./.github/workflows/z_qemu_test_run.yml
    secrets: inherit
