name: mips64-n32-4.19.56

on:
  push:
    branches:
      - master



jobs:

  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-mips64_mips64-gcc_n32-13.2.0
      gcc_prefix: mips64-openadk-linux-uclibcabin32-
      kernel_vers: 4.19.56
      kernel_dir: v4.x
      kernel_arch: mips
      config_file: config.mips64-n32
      qemu_kernel: kernel-mips64-n32.img
      qemu_cmd: qemu-system-mips64 -kernel kernel.img -initrd rootfs.img -append "console=ttyS0" -m 512M -nographic

  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    secrets: inherit
    
    
  call_qemu:
    needs: call_images
    uses: ./.github/workflows/z_qemu_test_run.yml
    secrets: inherit 
