name: xtensa-4.19.56

on:
  push:
    branches:
      - master


jobs:

  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-xtensa_dc233c-gcc-10_nommu
      gcc_prefix: xtensa-openadk-linux-uclibc-
      kernel_vers: 4.19.56
      kernel_dir: v4.x
      kernel_arch: xtensa
      config_file: config.xtensa
      qemu_kernel: 
      qemu_cmd: 

#  call_images:
#    needs: call_build
#    uses: ./.github/workflows/z_images_workflow.yml
