name: nds32le

on:
  push:
    branches:
      - master



jobs:

  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-nds32le_nds32-gcc-13.2.0
      gcc_prefix: nds32le-openadk-linux-uclibc-
      kernel_vers: 5.15.128
      kernel_dir: v5.x
      kernel_arch: nds32
      config_file: config.nds32le
      qemu_kernel: 
      qemu_cmd: 

  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    secrets: inherit
    
