name: bfin

on:
  push:
    branches:
      - master


#           wget "https://github.com/lordrasmus/toolchains/blob/main/blackfin-toolchain-elf-gcc-4.5-2014R1_45-RC2.x86_64.tar.bz2?raw=true" -O blackfin-toolchain-elf-gcc-4.5-2014R1_45-RC2.x86_64.tar.bz2
#           tar -xaf blackfin-toolchain-elf-gcc-4.5-2014R1_45-RC2.x86_64.tar.bz2
#           mv opt/uClinux/bfin-elf .
#           rm -rf opt
#      - name: add PATH
#        run: echo "$(pwd)/bfin-elf/bin/" >> $GITHUB_PATH

#      - name: Run Build
#        run: cp .github/workflows/config.bfin .config && PATH=$PATH:bfin-elf/bin CROSS_COMPILE=bfin-elf- make
      
      
jobs:
      
  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-bfin_bf512-gcc-13_flat_nommu
      gcc_prefix: bfin-openadk-uclinux-uclibc-
      kernel_vers: 4.9.156
      kernel_dir: v4.x
      kernel_arch: blackfin
      config_file: config.bfin2
      qemu_kernel: 
      qemu_cmd: 

# call_images:
#    needs: call_build
#    uses: ./.github/workflows/z_images_workflow.yml
#    secrets: inherit
    
