name: h8300h-no-gcc-13-kernel-4.4.302-static-nommu-flat

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master



jobs:
      
  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-h8300_h83000h-gcc-13.2.0_nommu_static
      gcc_prefix: h8300-openadk-linux-uclibc-
      kernel_vers: 4.4.302
      kernel_dir: v4.x
      kernel_arch: h8300
      config_file: config.h8300
      qemu_kernel: 
      qemu_cmd: 

#
#   hier geht schon der compiler aus openadk nicht
#
#             cannot find -lgcc: Datei oder Verzeichnis nicht gefunden
#
#  call_images:
#    needs: call_build
#    uses: ./.github/workflows/z_images_workflow.yml
#    secrets: inherit
    
