name: ia64

on:
  push:
    branches:
      - master



jobs:
      
  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-ia64-gcc-13
      gcc_prefix: ia64-openadk-linux-uclibc-
      kernel_vers: 6.1.53
      kernel_dir: v6.x
      kernel_arch: ia64
      config_file: config.ia64
      qemu_kernel: 
      qemu_cmd: 


  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    secrets: inherit
    
