name: avr32-lt-gcc-4-kernel-4.4.302-shared-elf

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master



jobs:

  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-avr32-gcc-4.4.7
      gcc_prefix: avr32-openadk-linux-uclibc-
      kernel_vers: 4.4.302
      kernel_dir: v4.x
      kernel_arch: avr32
      config_file: config.avr32
      qemu_kernel: 
      qemu_cmd: 


  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    secrets: inherit
    
