name: mips64-le-n32-lt-gcc-13-kernel-6.1.60-shared-elf

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master



jobs:
      
  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-mips64el_mips64-gcc_n32-13.2.0
      gcc_prefix: mips64el-openadk-linux-uclibcabin32-
      kernel_vers: 6.1.60
      kernel_dir: v6.x
      kernel_arch: mips
      config_file: config.mips64le-n32
      qemu_kernel: kernel-mips64le-n32.img
      qemu_cmd: qemu-system-mips64el -kernel kernel.img -initrd rootfs.img -append "console=ttyS0" -m 512M -nographic

  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    secrets: inherit
    

  call_qemu:
    needs: call_images
    uses: ./.github/workflows/z_qemu_test_run.yml
    secrets: inherit 
