name: hppa

on:
  push:
    branches:
      - master

jobs:
      
  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-hppa-gcc-13
      gcc_prefix: hppa-openadk-linux-uclibc-
      kernel_vers: 6.1.53
      kernel_dir: v6.x
      kernel_arch: parisc
      config_file: config.hppa
      qemu_kernel: kernel-hppa.img
      qemu_cmd:  qemu-system-hppa -kernel  kernel.img -initrd rootfs.img -nographic

  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    secrets: inherit
    
  call_qemu:
    permissions:
     checks: write
     pull-requests: write
     
    needs: call_images
    uses: ./.github/workflows/z_qemu_test_run.yml
    secrets: inherit
