name: microblazeel

on:
  push:
    branches:
      - master

jobs:
      
  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-microblazeel_gcc-12
      gcc_prefix: microblazeel-openadk-linux-uclibc-
      kernel_vers: 5.4.259
      kernel_dir: v5.x
      kernel_arch: microblaze
      config_file: config.microblazeel
      qemu_kernel: 
      qemu_cmd: 

  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    secrets: inherit
    
