name: h8300

on:
  push:
    branches:
      - master2


jobs:
      
  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-h8300-gcc-13_nommu
      gcc_prefix: h8300-openadk-linux-uclibc-
      kernel_vers: 4.4.302
      kernel_dir: v4.x
      kernel_arch: h8300
      config_file: config.h8300
      qemu_kernel: 
      qemu_cmd: 

#  call_images:
#    needs: call_build
#    uses: ./.github/workflows/z_images_workflow.yml
#    secrets: inherit
    
