name: riscv32-4.19.56

on:
  push:
    branches:
      - master



jobs:

  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-riscv32-gcc-10_nommu
      gcc_prefix: riscv32-openadk-linux-uclibc-
      kernel_vers: 4.19.56
      kernel_dir: v4.x
      kernel_arch: riscv
      config_file: config.riscv32
      qemu_kernel: kernel-riscv32.img
      qemu_cmd: qemu-system-riscv32 -M virt -nographic -kernel kernel.img -initrd rootfs.img


  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    secrets: inherit
    
