name: aarch64

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install dev packages
        run: sudo apt-get install gcc-aarch64-linux-gnu

      - name: Extract Kernel Headers
        run: wget https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.19.56.tar.xz && tar -xaf linux-4.19.56.tar.xz
      - name: Install Kernel Headers
        run: make -C linux-4.19.56/ INSTALL_HDR_PATH=$(pwd)/linux-headers/ headers_install ARCH=arm64

      - name: Run Makefile
        run: cp .github/workflows/config.aarch64 .config && CROSS_COMPILE=aarch64-linux-gnu- make
