name: sh2-4.19.56

on:
  push:
    branches:
      - disabled

      
jobs:

  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain_generic-sh_uclibc-ng_sh2eb_nommu
      gcc_prefix: sh2eb-openadk-linux-uclibc-
      kernel_vers: 4.19.56
      kernel_dir: v4.x
      kernel_arch: sh
      config_file: config.sh2eb
      qemu_kernel:
      qemu_cmd:

  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
