name: mips64le-n64-6.1.60

on:
  push:
    branches:
      - disabled

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install dev packages
        run: |
          sudo apt-get update
          sudo apt-get install gcc-mips64el-linux-gnuabi64

      - name: Extract Kernel Headers
        run: wget "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.1.60.tar.xz" -O linux-6.1.60.tar.xz && tar -xaf linux-6.1.60.tar.xz
      - name: Install Kernel Headers
        run: make -C linux-6.1.60/ INSTALL_HDR_PATH=$(pwd)/linux-headers/ headers_install ARCH=mips

      - name: Run shared
        run: |
          cp .github/workflows/config.mips64le-n64 .config && CROSS_COMPILE=mips64el-linux-gnuabi64- make
          readelf -A lib/libc.so.1  | head -n20

      
