name: mips64-n32-6.1.60

on:
  push:
    branches:
      - disabled

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install dev packages
        run: |
          sudo apt-get update
          sudo apt-get install tar

      - name: Install Toolchain
        run: |
           wget "https://github.com/lordrasmus/toolchains/blob/main/toolchain_generic-mips64_uclibc-ng_mips64_n32.tar.xz?raw=true" -O toolchain_generic-mips64_uclibc-ng_mips64_n32.tar.xz
           tar -xaf toolchain_generic-mips64_uclibc-ng_mips64_n32.tar.xz

      - name: add PATH
        run: echo "$(pwd)/toolchain_generic-mips64_uclibc-ng_mips64_n32/usr/bin/" >> $GITHUB_PATH

      - name: Extract Kernel Headers
        run: wget "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.1.60.tar.xz" -O linux-6.1.60.tar.xz && tar -xaf linux-6.1.60.tar.xz

      - name: Install Kernel Headers
        run: make -C linux-6.1.60/ INSTALL_HDR_PATH=$(pwd)/linux-headers/ headers_install ARCH=mips

      - name: Run shared
        run: cp .github/workflows/config.mips64-n32 .config && CROSS_COMPILE=mips64-openadk-linux-uclibcabin32- make

      
