name: kvx-v1-npt-gcc-9-kernel-kvx-shared-elf

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master



jobs:
      
  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-kvx-gcc-9.4.1
      gcc_prefix: kvx-openadk-linux-uclibc-
      kernel_vers: kvx
      kernel_dir: v6.x
      kernel_arch: kvx
      config_file: config.kvx
      qemu_kernel: kernel-kvx.img
      qemu_cmd: qemu-system-kvx -kernel kernel.img -m 1024M  -nographic


  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    secrets: inherit
    
    
  call_qemu:    
    needs: call_images
    uses: ./.github/workflows/z_qemu_test_run.yml
    secrets: inherit
