name: sh2-be-no-gcc-10-kernel-4.19.56-static-nommu-flat

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

      
jobs:

  call_build:
    uses: ./.github/workflows/z_build_workflow.yml
    with:
      toolchain: toolchain-sh2eb_sh2-gcc-10_nommu
      gcc_prefix: sh2eb-openadk-linux-uclibc-
      kernel_vers: 4.19.56
      kernel_dir: v4.x
      kernel_arch: sh
      config_file: config.sh2eb
      qemu_kernel:
      qemu_cmd:

  call_images:
    needs: call_build
    uses: ./.github/workflows/z_images_workflow.yml
    secrets: inherit
