name: z_qemu_test_run

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
     checks: write
     pull-requests: write
  
    steps:
    
      - name: Install qemu / python3 junit_xml
        run: sudo apt-get -y update; sudo apt-get install -y qemu-system python3-junit.xml
        
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: Qemu_Images
       # Use the output from the reusable workflow to upload the artifacts
      - name: Infos
        run: |
           jq '.' infos.json
      
      - name: parse Config JSON
        id: parse-json
        run: |
          json=$(cat infos.json)
          for key in $(echo "$json" | jq -r 'keys[]'); do
            value=$(echo "$json" | jq -r ".$key")
            echo "$key=$value" >> "$GITHUB_ENV"
          done
          
      - name: run Qemu
        run: |
           python3 .github/tools/run_qemu.py
           python3 .github/tools/read_test_log.py
    
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.7.0
        with:
          files: "test_result.xml"

      - name: upload 
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: Test_Result
          path: |
             log.txt
